### ISSUE TITLE
Stworzenie designu popup

### ISSUE THREAD

**Issue by Ewa2707** [POP-grupa-K/POP-system-obliczen-wysokoskalowych#15]

**Comment by JCeluch** [comment]
Wykorzystany zostanie React UI framework: [Material-UI](https://material-ui.com)
Projekt designu został wykonany w narzędziu Fimga: [projekt](https://www.figma.com/file/55Cgq3VRt97RQjRrfgCAj7/POPek?node-id=6%3A78)

**Comment by KamilKwapisz** [comment]
Jest git 👍
