### ISSUE TITLE
Ustalenie konwencji nazewniczej 

### ISSUE THREAD

**Issue by Ewa2707** [POP-grupa-K/POP-system-obliczen-wysokoskalowych#24]

**Comment by KamilKwapisz** [comment]
@Lukas2018 @Pyrrun Czy konwencje zastosowane [tutaj ](https://github.com/POP-grupa-K/appstore-service/blob/develop/docker-compose.yml) czyli nazwy `appstore_service`, `datashelf_service`,  `computation_cockpit_service` i [tutaj](https://github.com/POP-grupa-K/docker-setup/blob/master/docker-compose.yml) zostawiamy?

**Comment by Pyrrun** [comment]
zostawiamy
