### ISSUE TITLE
Zdefiniowanie pól w bazie danych

### ISSUE THREAD

**Issue by Ewa2707** [POP-grupa-K/POP-system-obliczen-wysokoskalowych#61]

**Comment by ivanprokopets** [comment]
[pola_bazy_danych_cropped.pdf](https://github.com/POP-grupa-K/POP-system-obliczen-wysokoskalowych/files/5439495/pola_bazy_danych_cropped.pdf)

**Comment by ivanprokopets** [comment]
update 
[definition_column_table_db_cropped.pdf](https://github.com/POP-grupa-K/POP-system-obliczen-wysokoskalowych/files/5444790/definition_column_table_db_cropped.pdf)
