### ISSUE TITLE
Stworzenie designu komponentu aktualizacji

### ISSUE THREAD

**Issue by JCeluch** [POP-grupa-K/POP-system-obliczen-wysokoskalowych#72]

**Comment by JCeluch** [comment]
Desing pod [linkiem](https://www.figma.com/file/55Cgq3VRt97RQjRrfgCAj7/POPek?node-id=147%3A0)

**Comment by KamilKwapisz** [comment]
> Desing pod [linkiem](https://www.figma.com/file/55Cgq3VRt97RQjRrfgCAj7/POPek?node-id=147%3A0)

Super!
